version: '3.8'
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - "4000:4000"
      - "15432:15432"
    environment:
      - CUBEJS_DEV_MODE=true
      # - CUBEJS_DB_HOST=postgres
      # - CUBEJS_DB_NAME=gc_db
      # - CUBEJS_DB_USER=gc_user
      # - CUBEJS_DB_PASS=root_password
      # - CUBEJS_DB_PORT=5432
    volumes:
      - .:/cube/conf
    depends_on:
      - postgres
    networks:
      - backend-network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  django:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static  # Mount volume for static files
      - media_volume:/app/media    # Mount volume for media files
    depends_on:
      - postgres  # Fixed db to postgres
      - redis
    command: >
      sh -c "python manage.py makemigrations || echo 'makemigrations failed'; 
            python manage.py migrate || echo 'migrate failed'; 
            python manage.py collectstatic --noinput || echo 'collectstatic failed';  
            python manage.py mqtt_subscribe & 
            daphne -b 0.0.0.0 -p 8000 Golden_Care.asgi:application"
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static  # Serve static files
      - media_volume:/app/media    # Serve media files
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - backend-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend-network

  ftp:
    image: fauria/vsftpd
    environment:
      - FTP_USER=user  # Your FTP username
      - FTP_PASS=password  # Your FTP password
      - PASV_ADDRESS=127.0.0.1  # You can replace with your server's IP or domain name
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - FILE_OPEN_MODE=0666
      - LOCAL_UMASK=022
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"  # FTP passive ports
    volumes:
      - static_volume:/home/vsftpd/static  # Map static files to FTP
      - media_volume:/home/vsftpd/media    # Map media files to FTP
    networks:
      - backend-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend-network:
