# Generated by Django 5.1.2 on 2024-10-18 14:51

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('All', 'ALL'), ('ECDE & Pre-Primary', 'ECDE & Pre-Primary'), ('Primary School', 'Primary School'), ('Junior Secondary', 'Junior School'), ('Secondary School', 'Secondary School')], default='Private', max_length=50)),
                ('Provider_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi Metropolitan'), ('Nakuru', 'Nakuru one'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], default='nairobi', max_length=50)),
                ('level', models.CharField(choices=[('All', 'ALL'), ('ECDE & Pre-Primary', 'ECDE & Pre-Primary'), ('Primary School', 'Primary School'), ('Junior Secondary', 'Junior School'), ('Secondary School', 'Secondary School')], default='preprimary', max_length=50)),
                ('curriculum', models.CharField(choices=[('CBC', 'CBC'), ('IGCSE', 'IGCSE'), ('ALL', 'ALL')], default='all', max_length=50)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
            bases=('userManager.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='customuser_ptr',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Provider', 'Provider'), ('admin', 'Admin')], default='Patient', max_length=50),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Patient', max_length=50)),
                ('emergency_contact', models.ManyToManyField(blank=True, related_name='Patients_with_contact', to='userManager.emergencycontact')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            bases=('userManager.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='Patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_emergency_contacts', to='userManager.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
