# Generated by Django 5.1.2 on 2024-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='bmi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_disease',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_history',
            field=models.BooleanField(default=False),
        ),
    ]
