# Generated by Django 5.1.2 on 2024-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_provider_remove_emergencycontact_individual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='level',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_vitals_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='vitals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='assigned_providers', to='userManager.patient'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('admin', 'Admin')], default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=50),
        ),
    ]
