# Generated by Django 5.1.2 on 2024-10-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0003_remove_provider_curriculum_remove_provider_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_vitals_update',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vitals',
        ),
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
